import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SupabaseProvider from '@/providers/SupabaseProvider'
import ProfileBootstrap from '@/providers/ProfileBootstrap'
import "./globals.css";
import { Toaster } from "sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-b from-[#EFF6FF] via-[#FFFFFF] to-[#DBEAFE]`}
      >
        <SupabaseProvider>
          <ProfileBootstrap />  {/* ⭐ This was the missing piece! */}
          {children}
          <Toaster position="top-right" richColors />
        </SupabaseProvider>
      </body>
    </html>
  );
}



// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import SupabaseProvider from '@/providers/SupabaseProvider'
// import "./globals.css";
// import { Toaster } from "sonner"

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
  
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-b from-[#EFF6FF] via-[#FFFFFF] to-[#DBEAFE]`}
//         >
//         <SupabaseProvider>
//           {children}
//           <Toaster position="top-right" richColors /> {/* ✅ new Shadcn/Sonner toast system */}
//         </SupabaseProvider>
//       </body>
//     </html>
        
//   );
// }
